### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by yangjl** [vsbuffalo/tasselr#1] opened 2015-04-15 05:41 UTC
Hi Vince,

I tried to install tasselr, but it threw me the following error. Could you look into it and see what else can I do? Thanks!

I use Mac with R 3.1.2.
x86_64-apple-darwin13.4.0/3.1.2

Regards,
-Jinliang

/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iterator:341:10: fatal error: '__debug' file not found
# include <__debug>

```
     ^
```

1 error generated.
make: **\* [RcppExports.o] Error 1
ERROR: compilation failed for package ‘tasselr’
- removing ‘~/Documents/Github/SeeDs/packrat/lib/x86_64-apple-darwin13.4.0/3.1.2/tasselr’
  Error: Command failed (1)

**Comment by vsbuffalo** [comment] 2015-04-15 05:43
Hi @yangjl — could you share your `sessionInfo()` to provide package versions, etc.?

**Comment by yangjl** [comment] 2015-04-15 05:52
Hi Vince,

Thanks for you quick response. Below paste my sessionInfo():

—

R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] devtools_1.7.0

loaded via a namespace (and not attached):
[1] bitops_1.0-6     httr_0.6.1       packrat_0.4.0.12
[4] RCurl_1.95-4.5   stringr_0.6.2    tools_3.1.2 

> On Apr 14, 2015, at 10:43 PM, Vince Buffalo notifications@github.com wrote:
> 
> Hi @yangjl https://github.com/yangjl — could you share your sessionInfo() to provide package versions, etc.?
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/vsbuffalo/tasselr/issues/1#issuecomment-93203858.

## 

Jinliang Yang

Dept. of Plant Sciences
262 Robbins Hall, Mail Stop 4
University of California
One Shields Ave
Davis, CA 95616

**Comment by vsbuffalo** [comment] 2015-04-15 06:01
Hmm, could be issue with rhdf5— could you do:

```
> library(rhdf5)
> sessionInfo()
```

(installing rhdf5 if you don't have it.)

**Comment by yangjl** [comment] 2015-04-15 06:03
> library(rhdf5)
> sessionInfo()
> R version 3.1.2 (2014-10-31)
> Platform: x86_64-apple-darwin13.4.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] rhdf5_2.10.0   devtools_1.7.0

loaded via a namespace (and not attached):
[1] bitops_1.0-6     httr_0.6.1       packrat_0.4.0.12
[4] RCurl_1.95-4.5   stringr_0.6.2    tools_3.1.2  
[7] zlibbioc_1.12.0 

> On Apr 14, 2015, at 11:01 PM, Vince Buffalo notifications@github.com wrote:
> 
> Hmm, could be issue with rhdf5— could you do:
> 
> > library(rhdf5)
> > sessionInfo()
> > (installing rhdf5 if you don't have it.)
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/vsbuffalo/tasselr/issues/1#issuecomment-93207663.

## 

Jinliang Yang

Dept. of Plant Sciences
262 Robbins Hall, Mail Stop 4
University of California
One Shields Ave
Davis, CA 95616

**Comment by vsbuffalo** [comment] 2015-04-15 06:06
Let's just get updated to check some stuff:

```
library(BiocInstaller)
biocValid() # share this with me
biocLite() # say "a"
```

and then:

```
library(Rcpp)
sessionInfo()
```

**Comment by yangjl** [comment] 2015-04-15 06:13
> install_github("vsbuffalo/tasselr")
> Downloading github repo vsbuffalo/tasselr@master
> Installing tasselr
> '/Library/Frameworks/R.framework/Resources/bin/R' --vanilla CMD INSTALL  \
>   '/private/var/folders/y8/gz0qvd7110114ql_br5z9szr0000gn/T/RtmpaRZCFv/devtools9a7324d6e8e6/vsbuffalo-tasselr-3cddff9'  \
>   --library='/Users/yangjl/Documents/Github/SeeDs/packrat/lib/x86_64-apple-darwin13.4.0/3.1.2'  \
>   --install-tests 
- installing _source_ package ‘tasselr’ ...
  *\* libs
  clang++ -std=c++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Users/yangjl/Documents/Github/SeeDs/packrat/lib/x86_64-apple-darwin13.4.0/3.1.2/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2 -c RcppExports.cpp -o RcppExports.o
  In file included from RcppExports.cpp:4:
  In file included from /Users/yangjl/Documents/Github/SeeDs/packrat/lib/x86_64-apple-darwin13.4.0/3.1.2/Rcpp/include/Rcpp.h:27:
  In file included from /Users/yangjl/Documents/Github/SeeDs/packrat/lib/x86_64-apple-darwin13.4.0/3.1.2/Rcpp/include/RcppCommon.h:29:
  In file included from /Users/yangjl/Documents/Github/SeeDs/packrat/lib/x86_64-apple-darwin13.4.0/3.1.2/Rcpp/include/Rcpp/platform/compiler.h:148:
  In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/unordered_map:350:
  In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__hash_table:16:
  In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:604:
  /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iterator:341:10: fatal error: '__debug' file not found
  #include <__debug>
       ^
  1 error generated.
  make: **\* [RcppExports.o] Error 1
  ERROR: compilation failed for package ‘tasselr’
- removing ‘/Users/yangjl/Documents/Github/SeeDs/packrat/lib/x86_64-apple-darwin13.4.0/3.1.2/tasselr’
  Error: Command failed (1)

> biocValid()
> [1] TRUE
> library(Rcpp)
> sessionInfo()
> R version 3.1.2 (2014-10-31)
> Platform: x86_64-apple-darwin13.4.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rcpp_0.11.5          BiocInstaller_1.16.2 rhdf5_2.10.0  
[4] devtools_1.7.0      

loaded via a namespace (and not attached):
[1] bitops_1.0-6    httr_0.6.1      packrat_0.4.3   RCurl_1.95-4.5 
[5] stringr_0.6.2   tools_3.1.2     zlibbioc_1.12.0

> On Apr 14, 2015, at 11:06 PM, Vince Buffalo notifications@github.com wrote:
> 
> Let's just get updated to check some stuff:
> 
> library(BiocInstaller)
> biocValid() # share this with me
> biocLite() # say "a"
> and then:
> 
> library(Rcpp)
> sessionInfo()
> —
> Reply to this email directly or view it on GitHub https://github.com/vsbuffalo/tasselr/issues/1#issuecomment-93209826.

## 

Jinliang Yang

Dept. of Plant Sciences
262 Robbins Hall, Mail Stop 4
University of California
One Shields Ave
Davis, CA 95616

**Comment by vsbuffalo** [comment] 2015-04-15 06:18
Now, in the shell:

```
clang++ --version
```

**Comment by yangjl** [comment] 2015-04-15 06:19
Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix

> On Apr 14, 2015, at 11:18 PM, Vince Buffalo notifications@github.com wrote:
> 
> Now, in the shell:
> 
> clang++ --version
> —
> Reply to this email directly or view it on GitHub https://github.com/vsbuffalo/tasselr/issues/1#issuecomment-93216536.

## 

Jinliang Yang

Dept. of Plant Sciences
262 Robbins Hall, Mail Stop 4
University of California
One Shields Ave
Davis, CA 95616

**Comment by vsbuffalo** [comment] 2015-04-15 06:24
and:

```
brew info hdf5 # or some other way to find hdf5 version
```

Still stumped, so lots of info gathering. I may go to bed soon, but we can continue tomorrow.

**Comment by yangjl** [comment] 2015-04-15 06:29
Vince,

I do not know how to check hdf5. I will go to bed soon. Let us do it tomorrow or later.
Or can you tell me how to interpret the following dataset in the hdf5? I may be able to do it in Python.

file["/Genotypes/6102-31:250007332"]
array([34, 34, 34, 34, -1, -1, -1, -1, -1], dtype=int8)

> On Apr 14, 2015, at 11:24 PM, Vince Buffalo notifications@github.com wrote:
> 
> and:
> 
> brew info hdf5 # or some other way to find hdf5 version
> Still stumped, so lots of info gathering. I may go to bed soon, but we can continue tomorrow.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/vsbuffalo/tasselr/issues/1#issuecomment-93217674.

## 

Jinliang Yang

Dept. of Plant Sciences
262 Robbins Hall, Mail Stop 4
University of California
One Shields Ave
Davis, CA 95616

**Comment by vsbuffalo** [comment] 2015-04-15 06:45
Ok, this appears to be an upstream issue with Apple's new command line tools version. Please see:

http://stackoverflow.com/questions/29529455/missing-c-header-debug-after-updating-osx-command-line-tools-6-3

I'm going to close the issue since this is what appears to be the problem but please do reopen if this doesn't work. Thanks for using tasselr!!

**Comment by vsbuffalo** [comment] 2015-04-15 19:48
Did this work @yangjl?

**Comment by yangjl** [comment] 2015-04-15 19:56
Unfortunately NO. But, do not worry about it. I will just export the data with tassel.

> On Apr 15, 2015, at 12:48 PM, Vince Buffalo notifications@github.com wrote:
> 
> Did this work @yangjl https://github.com/yangjl?
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/vsbuffalo/tasselr/issues/1#issuecomment-93545761.

## 

Jinliang Yang

Dept. of Plant Sciences
262 Robbins Hall, Mail Stop 4
University of California
One Shields Ave
Davis, CA 95616

**Comment by vsbuffalo** [comment] 2015-04-15 20:04
Well, we should try to solve the issue:

(1) HDF5 is an incredibly good format to work with — it's insanely fast and compressed (even NASA uses it). Frankly, we're lucky Tassel outputs data in this format; there's no reason to convert huge data to text just because of a software bug that will ultimately be fixed. Also, loading data into R via HDF5 takes a few minutes on a 16GB RAM machine, while loading text data of this magnitude in R will likely hit swap space and take forever (it did for me, which is why I wrote tasselr).

(2) Others in the maize community use tasselr, and you and I sorting out this issue will prevent headaches in the future.

Do you get the same error with the new command line tools? Can you give me the version of Xcode you have (and try upgrading, and try again)? @kate-crosby mentioned she had the same issue. I cannot reproduce it on my machine; everything installs fine.

**Comment by yangjl** [comment] 2015-04-15 20:08
Can you install it on farm? Cause farm is the common enviroment we are using. If tasselr can install there, all of us will be fine to load data.

> On Apr 15, 2015, at 1:04 PM, Vince Buffalo notifications@github.com wrote:
> 
> Well, we should try to solve the issue:
> 
> (1) HDF5 is an incredibly good format to work with — it's insanely fast and compressed (even NASA uses it). Frankly, we're lucky Tassel outputs data in this format; there's no reason to convert huge data to text just because of a software bug that will ultimately be fixed. Also, loading data into R via HDF5 takes a few minutes on a 16GB RAM machine, while loading text data of this magnitude in R will likely hit swap space and take forever (it did for me, which is why I wrote tasselr).
> 
> (2) Others in the maize community use tasselr, and you and I sorting out this issue will prevent headaches in the future.
> 
> Do you get the same error with the new command line tools? Can you give me the version of Xcode you have (and try upgrading, and try again)? @kate-crosby https://github.com/kate-crosby mentioned she had the same issue. I cannot reproduce it on my machine; everything installs fine.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/vsbuffalo/tasselr/issues/1#issuecomment-93550558.

## 

Jinliang Yang

Dept. of Plant Sciences
262 Robbins Hall, Mail Stop 4
University of California
One Shields Ave
Davis, CA 95616

**Comment by vsbuffalo** [comment] 2015-04-15 20:11
@yangjl Yes it installs fine on Farm (I am convinced this is still related to the OS X command line tools issue — it appears that update broke a lot of software if you Google around).

```
library(devtools)
install_github('vsbuffalo/tasselr')
library(tasselr)
```

Everything works on farm — just tried it.

**Comment by kate-crosby** [comment] 2015-04-15 20:57
Yup! For me too. All good.

**Comment by yangjl** [comment] 2015-04-15 21:15
Vince,

I got it installed on farm. I am convinced it is related to the Xcode update issue too.
I updated to Xcode 6.4, however,  it threw me the same error. I can find no where to downgrade the software.

For now, it works for linux system, but not for upgraded OX X 10.10 with Xcode 6.3 or Xcode 6.4.

> On Apr 15, 2015, at 1:57 PM, Kate Crosby notifications@github.com wrote:
> 
> Yup! For me too. All good.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/vsbuffalo/tasselr/issues/1#issuecomment-93567318.

## 

Jinliang Yang

Dept. of Plant Sciences
262 Robbins Hall, Mail Stop 4
University of California
One Shields Ave
Davis, CA 95616

**Comment by vsbuffalo** [comment] 2015-04-16 17:18
@yangjl Per [this thread](https://github.com/JuliaLang/julia/issues/10822) try:

```
echo '#define _LIBCPP_ASSERT(x, m) ((void)0)' | sudo tee -a /Library/Developer/CommandLineTools/usr/include/c++/v1/__debug > /dev/null
```

Looks like Apple didn't test the new release, and this is breaking many programs.

**Comment by vsbuffalo** [comment] 2015-04-16 17:22
Though do note, this is mucking about with system headers, which isn't optimal.

**Comment by vsbuffalo** [comment] 2015-04-16 17:23
Here's the [link to command line tools 6.2](https://developer.apple.com/downloads/index.action) — this is the recommended way to get around this issue.

**Closed as completed by vsbuffalo** 2015-04-16 17:23 UTC
